specVersion: "0.1"
kind: Project
metadata: {id: inventory-api, name: Inventory API}
spec:
  workflow: delivery
  quality:
    - characteristic: reliability
      subcharacteristics:
        - subcharacteristic: availability
          requirements: [api-availability]
providers:
  workManagement:
    provider: jira-cloud
    config:
      baseURL: https://example.atlassian.net
      projectKey: INV
      projectTemplateKey: com.pyxis.greenhopper.jira:gh-kanban-template
      issueTypeName: Task
      members:
        - role: software-engineer
          emails: [engineer@example.com]
          jiraProjectRole: Members
      kanban:
        columns: [To do, In progress, Done]
